### ISSUE TITLE
项目启动时es报错，跪求指点

### ISSUE THREAD

**Issue by zhimy** [llldddbbb/dbblog#3]
2019-04-23 16:30:44.128 ERROR 20892 --- [           main] .d.e.r.s.AbstractElasticsearchRepository : failed to load elasticsearch nodes : org.elasticsearch.client.transport.NoNodeAvailableException: None of the configured nodes are available: [{#transport#-1}{WWsOM8x5TaqhBy1K3nR9Dw}{127.0.0.1}{127.0.0.1:9300}]
NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{WWsOM8x5TaqhBy1K3nR9Dw}{127.0.0.1}{127.0.0.1:9300}]]
	at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:349)
	at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:247)
	at org.elasticsearch.client.transport.TransportProxyClient.execute(TransportProxyClient.java:60)
	at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:381)
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:407)
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:396)
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:46)
	at org.springframework.data.elasticsearch.core.ElasticsearchTemplate.getSearchResponse(ElasticsearchTemplate.java:946)
	at org.springframework.data.elasticsearch.core.ElasticsearchTemplate.doScroll(ElasticsearchTemplate.java:808)
	at org.springframework.data.elasticsearch.core.ElasticsearchTemplate.startScroll(ElasticsearchTemplate.java:822)
	at org.springframework.data.elasticsearch.core.ElasticsearchTemplate.delete(ElasticsearchTemplate.java:719)

**Comment by llldddbbb** [comment]
你需要安装ES先

**Comment by zhimy** [comment]
系统对ES的版本有要求吗，我装的是6.2.2版本的 es和kibana 别的没有改了，然后就报错

**Comment by llldddbbb** [comment]
我装的是6.6.3。6.x按理说应该是可以的，报错说找不到ES节点，查看下ES是否启动，端口地址是否正确等

**Comment by daowolf** [comment]
Adding transport node : 127.0.0.1:9300,你配置文件http.port: 9200
#服务发现端口
transport.tcp.port: 9300
服务发现端口配了没

**Comment by zhimy** [comment]
我把es下载下来只是解压了，没有更改elasticsearch.yml配置文件。我需要配置那两个端口吗？
